name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 14.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build  
      run: npm build
    - name: Format
      run: npm run format
    - name: Lint
      run: npm run lint
    - name: Pack
      run: npm run pack
